CMD_STOP_SERVER = "stop tcp server"
CMD_START_TREX = "start trex"
CMD_STOP_TREX = "stop trex"
CMD_RECVD = "received command"
CMD_MEASURE_MLFFR = "measure mlffr"
CMD_CHECK_PKT_GEN_STABLE = "check packet gen stable"
