items:
  - input: /data/local/qx51/bpf-profile/dpdk_burst_replay/pcap_scripts/1flow.pcap
    output: /data/local/qx51/bpf-profile/dpdk_burst_replay/pcap_scripts/tmp/1flow
    num_cores: 9
    dst_mac: 10:70:fd:d6:a0:64
    tasks:
      - hhd: shared, flow_affinity, shared_nothing
      - ddos_mitigator: shared, flow_affinity, shared_nothing
      - token_bucket: shared, flow_affinity, shared_nothing
  - input: /data/local/qx51/bpf-profile/dpdk_burst_replay/pcap_scripts/3flow.pcap
    output: /data/local/qx51/bpf-profile/dpdk_burst_replay/pcap_scripts/tmp/3flow
    num_cores: 9
    dst_mac: 10:70:fd:d6:a0:64
    tasks:
      - hhd: shared, flow_affinity, shared_nothing
      - ddos_mitigator: shared, flow_affinity, shared_nothing
      - token_bucket: shared, flow_affinity, shared_nothing
