items:
  - input: /common/home/qx51/pcap_files_mtu1500_0905/20flow.pcap
    output: /common/home/qx51/pcap_files_mtu1500_0905/20flow_tcp/
    num_cores: 14
    tcp_only: true
    dst_mac: 10:70:fd:d6:a0:64
    pkt_len: 192
    tasks:
      - hhd: shared, flow_affinity, shared_nothing
      - token_bucket: shared, flow_affinity, shared_nothing
      - ddos_mitigator: shared, flow_affinity, shared_nothing
  - input: /common/home/qx51/pcap_files_mtu1500_0905/20flow.pcap
    output: /common/home/qx51/pcap_files_mtu1500_0905/20flow_tcp/
    num_cores: 14
    tcp_only: true
    dst_mac: 10:70:fd:d6:a0:64
    pkt_len: 128
    tasks:
      - hhd: shared, flow_affinity, shared_nothing
      - token_bucket: shared, flow_affinity, shared_nothing
      - ddos_mitigator: shared, flow_affinity, shared_nothing
